##############################################################################
# Select message passing interface (NONE, MPICH, LAMMPI)
##############################################################################

export MESSAGE_INTERFACE = NONE
#export MESSAGE_INTERFACE = MPICH
#export MESSAGE_INTERFACE = LAMMPI

##############################################################################
# Select compiler
##############################################################################

ifeq ($(MESSAGE_INTERFACE), MPICH)
    export ALPSCXX := mpiCC
endif

ifeq ($(MESSAGE_INTERFACE), LAMMPI)
    export ALPSCXX := hcp
endif

# Don't need to select compiler for the serial code, unless you don't 
# want to use the one COIN picks based on operating system.

ifeq ($(MESSAGE_INTERFACE), NONE)
    export ALPSCXX := $(CXX)
endif


##############################################################################
# Select optimization (-O or -g). -O will be automatically bumped up to the 
# highest level of optimization the compiler supports. If want something in
# between then specify the exact level you want, e.g., -O1 or -O2
##############################################################################

OptLevel := -g
#OptLevel := -O

##############################################################################
# Select static or shared libraries should be built
##############################################################################

ifeq ($(MESSAGE_INTERFACE), NONE)
    LibType := SHARED
    #LibType := STATIC
endif

ifeq ($(MESSAGE_INTERFACE), MPICH)
    LibType := STATIC
endif

ifeq ($(MESSAGE_INTERFACE), LAMMPI)
    LibType := STATIC
endif

##############################################################################
# Extra include dir and lib for MPI
##############################################################################

ifeq ($(MESSAGE_INTERFACE), MPICH)
#    MpiIncDir := /usr/mpi/mpich-1.2.3-3/include
    MpiLib :=
endif
ifeq ($(MESSAGE_INTERFACE), LAMMPI)
    MpiIncDir :=
#   MpiIncDir := /usr/mpi/lam-6.5.6/include
    MpiLib := libmpi
endif


##############################################################################
##############################################################################
# You should not need to edit below this line.
##############################################################################
##############################################################################
AlpsDefine :=
ifeq ($(MESSAGE_INTERFACE), NONE)
    AlpsDefine += ALPS_SERIAL
endif
ifeq ($(MESSAGE_INTERFACE), MPICH)
    AlpsDefine += ALPS_PARALLEL_MPI
endif
ifeq ($(MESSAGE_INTERFACE), LAMMPI)
    AlpsDefine += ALPS_PARALLEL_MPI
endif

##############################################################################

export LibType OptLevel MpiIncDir MpiLib AlpsDefine
export AlpsLibName := libAlps
