Description:
  Slug: CHiPPS-ALPS
  ShortName: Alps
  LongName: Abstract Library for Parallel Search.
  ShortDescription: A collection of abstract base classes for implementing parallel tree search.
  LongDescription: |2
    The Abstract Library for Parallel Search (ALPS) is a collection of abstract
    base classes that forms the base level of a class hierarchy comprising
    CHiPPS, the COIN-OR High Performance Parallel Search Framework. CHiPPS
    is a framework for implementing parallel algorithms based on tree search.
    The current CHiPPS hierarchy consists of three main layers (ALPS, BiCEPS,
    BLIS) upon which multiple applications are built.  
  Manager: Ted Ralphs, ted at lehigh dot edu 
  Homepage: https://github.com/coin-or/CHiPPS-ALPS
  License: Eclipse Public License 2.0
  LicenseURL: http://www.opensource.org/licenses/eclipse-2.0
  Zenodo: 23726893
  IncludedIn:
    Package: CHiPPS-BLIS
  Language:
    - C++
  Categories: 
    - Optimization deterministic linear discrete
    - Optimization utility
  PaperCite: http://dx.doi.org/10.1007/0-387-23529-9_21
  
Dependencies:
  - Description: COIN-OR Utilities
    URL: https://github.com/coin-or/CoinUtils
    Version: master
    Required: Required
  - Description: Open Solver Interface
    URL: https://github.com/coin-or/Osi
    Version: master
    Required: Required
  - Description: Open Solver Interface
    URL: https://github.com/coin-or/Clp
    Version: master
    Required: Recommended
  - Description: Open Solver Interface
    URL: https://github.com/coin-or/Cgl
    Version: master
    Required: Recommended
  - Description: Basic Linear Algebra Subroutines (BLAS)
    URL: http://www.netlib.org/blas
    Required: Optional
  - Description: Linear Algebra Package (LAPACK)
    URL: http://www.netlib.org/lapack
    Required: Optional
  - Description: GNU Readline
    Required: Recommended
  - Description: GNU History
    Required: Recommended

DevelopmentStatus: 
  activityStatus: Active
  maturityLevel: 5
  testedPlatforms: 
  - operatingSystem: Linux
    compiler: gcc
  - operatingSystem: Mac OS X
    compiler:
    - gcc
    - clang
  - operatingSystem: Microsoft Windows
    compiler: cl
  - operatingSystem: Microsoft Windows with MSys2
    compiler:
    - gcc
    - cl
    - icl
  - operatingSystem: Microsoft Windows Subsystem for Linux
    compiler:
    - gcc
    - cl
    - icl
