#include "AlpsLicense.h"

#ifndef AlpsAllPara_h
#define AlpsAllPara_h

//#############################################################################
//#############################################################################

//** Parameters used in Alps. */
struct AlpsAllParam{
  /** Character parameters. All of these variable are used as booleans
      (ture = 1, false = 0). */
  enum chrParams{
    // The dummy is needed so the allocation won't try for 0 entries.
    chrDummy,
    //
    endOfChrParams
  };

  /** Integer paramters. */
  enum intParams{
    /** The number of worker processes that be used. */
    workerProcessNum,
    /** The number of nodes initially generated by the master. */
    intialNodeNum,
    /** The size of memory allocated for AlpsEnocoded::type_ in message buf. */
    typeSize,
    //
    endOfIntParams
  };

  /** Double parameters. */
  enum dblParams{
    dblDummy, 
    //
    endOfDblParams
  };

  /** String parameters. */
  enum strParams{
    strDummy,
    //
    endOfStrParams
  };

  /** There are no string array parameters. */
  enum strArrayParams{
    strArrayDummy,
    //
    endOfStrArrayParams
  };

};

#endif
